package com.example.vidyarthibus3

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object AppSettings {
    var isDarkMode by mutableStateOf(false)
    var selectedLanguage by mutableStateOf("English")
}

val supportedLanguages = listOf("English", "ಕನ್ನಡ", "हिंदी", "മലയാളം")

data class AppStrings(
    val appName: String,
    val tagline: String,
    val searchRoute: String,
    val from: String,
    val to: String,
    val findMyBus: String,
    val pleaseSelect: String,
    val pleaseSelectSub: String,
    val crowdStatus: String,
    val contribute: String,
    val moreOptions: String,
    val scheduleStops: String,
    val viewAllTimings: String,
    val alternativeContacts: String,
    val autosCabsMore: String,
    val crowdMeter: String,
    val busApproaching: String,
    val empty: String,
    val moderate: String,
    val almostFull: String,
    val noRecentReports: String,
    val lastReportExpired: String,
    val basedOn: String,
    val passengerReports: String,
    val last5Min: String,
    val majority: String,
    val sameStopWarning: String,
    val settings: String,
    val language: String,
    val darkMode: String,
    val lightMode: String,
    val seated: String,
    val full: String,
    val startingStation: String,
    val destinationStation: String,
)

fun getStrings(language: String): AppStrings = when (language) {
    "ಕನ್ನಡ" -> AppStrings(
        appName = "ವಿದ್ಯಾರ್ಥಿ-ಬಸ್",
        tagline = "ವಿದ್ಯಾರ್ಥಿ ಸಾರಿಗೆ ಜಾಲ",
        searchRoute = "ಮಾರ್ಗ ಹುಡುಕಿ",
        from = "ಇಂದ", to = "ಗೆ",
        findMyBus = "ನನ್ನ ಬಸ್ ಹುಡುಕಿ",
        pleaseSelect = "ಬಸ್ ಮಾರ್ಗ ಆಯ್ಕೆ ಮಾಡಿ",
        pleaseSelectSub = "ಮೇಲೆ ನಿಮ್ಮ ನಿಲ್ದಾಣ ನಮೂದಿಸಿ",
        crowdStatus = "ಜನಸಂದಣಿ ಸ್ಥಿತಿ",
        contribute = "ವರದಿ ಮಾಡಿ",
        moreOptions = "ಹೆಚ್ಚಿನ ಆಯ್ಕೆಗಳು",
        scheduleStops = "ವೇಳಾಪಟ್ಟಿ\n& ನಿಲ್ದಾಣಗಳು",
        viewAllTimings = "ಎಲ್ಲಾ ಸಮಯ ನೋಡಿ",
        alternativeContacts = "ಪರ್ಯಾಯ\nಸಂಪರ್ಕಗಳು",
        autosCabsMore = "ಆಟೋ, ಕ್ಯಾಬ್ & ಹೆಚ್ಚು",
        crowdMeter = "ಜನಸಂದಣಿ ಮೀಟರ್",
        busApproaching = "ಬಸ್ ಬರುತ್ತಿದೆ",
        empty = "ಖಾಲಿ", moderate = "ಮಧ್ಯಮ", almostFull = "ತುಂಬಿದೆ",
        noRecentReports = "ಯಾವುದೇ ವರದಿ ಇಲ್ಲ",
        lastReportExpired = "⏱ ಕೊನೆಯ ವರದಿ ಅವಧಿ ಮೀರಿದೆ",
        basedOn = "ಆಧರಿಸಿ", passengerReports = "ಪ್ರಯಾಣಿಕ ವರದಿ",
        last5Min = "ಕೊನೆಯ 5 ನಿಮಿಷ", majority = "✓ ಬಹುಮತ",
        sameStopWarning = "⚠ ಆರಂಭ ಮತ್ತು ಗಮ್ಯ ನಿಲ್ದಾಣ ಒಂದೇ ಆಗಿರಬಾರದು",
        settings = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", language = "ಭಾಷೆ",
        darkMode = "ಡಾರ್ಕ್ ಮೋಡ್", lightMode = "ಲೈಟ್ ಮೋಡ್",
        seated = "ಕುಳಿತಿದ್ದಾರೆ", full = "ತುಂಬಿದೆ",
        startingStation = "ಆರಂಭ ನಿಲ್ದಾಣ", destinationStation = "ಗಮ್ಯ ನಿಲ್ದಾಣ",
    )
    "हिंदी" -> AppStrings(
        appName = "विद्यार्थी-बस",
        tagline = "छात्र परिवहन नेटवर्क",
        searchRoute = "मार्ग खोजें",
        from = "से", to = "तक",
        findMyBus = "मेरी बस खोजें",
        pleaseSelect = "बस मार्ग चुनें",
        pleaseSelectSub = "ऊपर अपना स्टेशन दर्ज करें",
        crowdStatus = "भीड़ स्थिति",
        contribute = "रिपोर्ट करें",
        moreOptions = "अधिक विकल्प",
        scheduleStops = "समय सारणी\n& स्टॉप",
        viewAllTimings = "सभी समय देखें",
        alternativeContacts = "वैकल्पिक\nसंपर्क",
        autosCabsMore = "ऑटो, कैब & अधिक",
        crowdMeter = "भीड़ मीटर",
        busApproaching = "बस आ रही है",
        empty = "खाली", moderate = "मध्यम", almostFull = "लगभग भरी",
        noRecentReports = "कोई हालिया रिपोर्ट नहीं",
        lastReportExpired = "⏱ अंतिम रिपोर्ट समाप्त हो गई",
        basedOn = "आधारित", passengerReports = "यात्री रिपोर्ट",
        last5Min = "पिछले 5 मिनट", majority = "✓ बहुमत",
        sameStopWarning = "⚠ शुरुआत और गंतव्य स्टेशन एक नहीं हो सकते",
        settings = "सेटिंग्स", language = "भाषा",
        darkMode = "डार्क मोड", lightMode = "लाइट मोड",
        seated = "बैठे हैं", full = "भरी है",
        startingStation = "शुरुआती स्टेशन", destinationStation = "गंतव्य स्टेशन",
    )
    "മലയാളം" -> AppStrings(
        appName = "വിദ്യാർഥി-ബസ്",
        tagline = "വിദ്യാർഥി ഗതാഗത ശൃംഖല",
        searchRoute = "റൂട്ട് തിരയുക",
        from = "നിന്ന്", to = "വരെ",
        findMyBus = "എന്റെ ബസ് കണ്ടെത്തുക",
        pleaseSelect = "ബസ് റൂട്ട് തിരഞ്ഞെടുക്കുക",
        pleaseSelectSub = "മുകളിൽ നിങ്ങളുടെ സ്റ്റേഷൻ നൽകുക",
        crowdStatus = "തിരക്ക് നില",
        contribute = "റിപ്പോർട്ട് ചെയ്യുക",
        moreOptions = "കൂടുതൽ ഓപ്ഷനുകൾ",
        scheduleStops = "ഷെഡ്യൂൾ\n& സ്റ്റോപ്പുകൾ",
        viewAllTimings = "എല്ലാ സമയവും കാണുക",
        alternativeContacts = "ബദൽ\nബന്ധപ്പെടൽ",
        autosCabsMore = "ഓട്ടോ, ക്യാബ് & കൂടുതൽ",
        crowdMeter = "തിരക്ക് മീറ്റർ",
        busApproaching = "ബസ് വരുന്നു",
        empty = "ഒഴിഞ്ഞ്", moderate = "മിതമായ", almostFull = "ഏതാണ്ട് നിറഞ്ഞ്",
        noRecentReports = "സമീപകാല റിപ്പോർട്ടുകൾ ഇല്ല",
        lastReportExpired = "⏱ അവസാന റിപ്പോർട്ട് കാലഹരണപ്പെട്ടു",
        basedOn = "അടിസ്ഥാനമാക്കി", passengerReports = "യാത്രക്കാരുടെ റിപ്പോർട്ട്",
        last5Min = "കഴിഞ്ഞ 5 മിനിറ്റ്", majority = "✓ ഭൂരിപക്ഷം",
        sameStopWarning = "⚠ ആരംഭ, ലക്ഷ്യ സ്റ്റേഷൻ ഒന്നാകരുത്",
        settings = "ക്രമീകരണങ്ങൾ", language = "ഭാഷ",
        darkMode = "ഡാർക്ക് മോഡ്", lightMode = "ലൈറ്റ് മോഡ്",
        seated = "ഇരിക്കുന്നു", full = "നിറഞ്ഞ്",
        startingStation = "ആരംഭ സ്റ്റേഷൻ", destinationStation = "ലക്ഷ്യ സ്റ്റേഷൻ",
    )
    else -> AppStrings(
        appName = "Vidyarthi-Bus",
        tagline = "STUDENT TRANSPORT NETWORK",
        searchRoute = "SEARCH ROUTE",
        from = "FROM", to = "TO",
        findMyBus = "FIND MY BUS",
        pleaseSelect = "PLEASE SELECT BUS ROUTE",
        pleaseSelectSub = "Enter your starting and destination\nstations above to find available buses.",
        crowdStatus = "CROWD STATUS",
        contribute = "CONTRIBUTE",
        moreOptions = "MORE OPTIONS",
        scheduleStops = "Schedule\n& Stops",
        viewAllTimings = "View all timings",
        alternativeContacts = "Alternative\nContacts",
        autosCabsMore = "Autos, cabs & more",
        crowdMeter = "CROWD METER",
        busApproaching = "IS APPROACHING",
        empty = "Empty", moderate = "MODERATE", almostFull = "ALMOST FULL",
        noRecentReports = "NO RECENT REPORTS",
        lastReportExpired = "⏱ Last report expired (> 5 min ago)",
        basedOn = "Based on", passengerReports = "passenger report",
        last5Min = "last 5 min", majority = "✓ majority",
        sameStopWarning = "⚠ From and To stops cannot be the same",
        settings = "Settings", language = "Language",
        darkMode = "Dark Mode", lightMode = "Light Mode",
        seated = "Seated", full = "Full",
        startingStation = "Starting Station", destinationStation = "Destination Station",
    )
}